package com.xx.modules.file.dao;

import com.xx.modules.file.om.FundCamcDividendMethodConfirm;

public interface FundCamcDividendMethodConfirmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_camc_dividend_method_confirm
     *
     * @mbggenerated Tue Feb 14 14:35:14 CST 2017
     */
    int insert(FundCamcDividendMethodConfirm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_camc_dividend_method_confirm
     *
     * @mbggenerated Tue Feb 14 14:35:14 CST 2017
     */
    int insertSelective(FundCamcDividendMethodConfirm record);
}