package com.xx.modules.file.dao;

import com.xx.modules.file.om.FundCamcTradeApply;

public interface FundCamcTradeApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_camc_trade_apply
     *
     * @mbggenerated Tue Feb 14 14:35:14 CST 2017
     */
    int insert(FundCamcTradeApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_camc_trade_apply
     *
     * @mbggenerated Tue Feb 14 14:35:14 CST 2017
     */
    int insertSelective(FundCamcTradeApply record);
}