package com.xx.modules.file.dao;

import com.xx.modules.file.om.FundCamcRedeemConfirm;

public interface FundCamcRedeemConfirmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_camc_redeem_confirm
     *
     * @mbggenerated Tue Feb 14 14:35:14 CST 2017
     */
    int insert(FundCamcRedeemConfirm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_camc_redeem_confirm
     *
     * @mbggenerated Tue Feb 14 14:35:14 CST 2017
     */
    int insertSelective(FundCamcRedeemConfirm record);
}