package com.xx.modules.file.dao;

import com.xx.modules.file.om.FundCamcAccountConfirmFailure;

public interface FundCamcAccountConfirmFailureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_camc_account_confirm_failure
     *
     * @mbggenerated Tue Feb 14 14:35:14 CST 2017
     */
    int insert(FundCamcAccountConfirmFailure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_camc_account_confirm_failure
     *
     * @mbggenerated Tue Feb 14 14:35:14 CST 2017
     */
    int insertSelective(FundCamcAccountConfirmFailure record);
}