package com.xx.modules.file.dao;

import com.xx.modules.file.om.FundCamcUserProfit;

public interface FundCamcUserProfitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_camc_user_profit
     *
     * @mbggenerated Tue Feb 14 14:35:14 CST 2017
     */
    int insert(FundCamcUserProfit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_camc_user_profit
     *
     * @mbggenerated Tue Feb 14 14:35:14 CST 2017
     */
    int insertSelective(FundCamcUserProfit record);
}