package com.xx.modules.file.dao;

import com.xx.modules.file.om.FundCamcUpdateCustomerInfo;

public interface FundCamcUpdateCustomerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_camc_update_customer_info
     *
     * @mbggenerated Tue Feb 14 14:35:14 CST 2017
     */
    int insert(FundCamcUpdateCustomerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_camc_update_customer_info
     *
     * @mbggenerated Tue Feb 14 14:35:14 CST 2017
     */
    int insertSelective(FundCamcUpdateCustomerInfo record);
}