package com.xx.modules.file.dao;

import com.xx.modules.file.om.FundCamcUserDetailProfit;

public interface FundCamcUserDetailProfitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_camc_user_detail_profit
     *
     * @mbggenerated Tue Feb 14 14:35:14 CST 2017
     */
    int insert(FundCamcUserDetailProfit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_camc_user_detail_profit
     *
     * @mbggenerated Tue Feb 14 14:35:14 CST 2017
     */
    int insertSelective(FundCamcUserDetailProfit record);
}