package com.xx.modules.file.dao;

import com.xx.modules.file.om.FundCamcPurchaseConfirm;

public interface FundCamcPurchaseConfirmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_camc_purchase_confirm
     *
     * @mbggenerated Tue Feb 14 14:35:14 CST 2017
     */
    int insert(FundCamcPurchaseConfirm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_camc_purchase_confirm
     *
     * @mbggenerated Tue Feb 14 14:35:14 CST 2017
     */
    int insertSelective(FundCamcPurchaseConfirm record);
}