package com.xx.modules.file.dao;

import com.xx.modules.file.om.FundCamcFundNav;

public interface FundCamcFundNavMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_camc_fund_nav
     *
     * @mbggenerated Tue Feb 14 14:35:14 CST 2017
     */
    int insert(FundCamcFundNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fund_camc_fund_nav
     *
     * @mbggenerated Tue Feb 14 14:35:14 CST 2017
     */
    int insertSelective(FundCamcFundNav record);
}